from .sort_nodes import NODE_CLASS_MAPPINGS as SORT_NODE_CLASSES
from .sort_nodes import NODE_DISPLAY_NAME_MAPPINGS as SORT_NODE_NAMES
from .video_nodes import NODE_CLASS_MAPPINGS as VIDEO_NODE_CLASSES
from .video_nodes import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_NODE_NAMES
from .filter_nodes import NODE_CLASS_MAPPINGS as FILTER_NODE_CLASSES
from .filter_nodes import NODE_DISPLAY_NAME_MAPPINGS as FILTER_NODE_NAMES
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(SORT_NODE_CLASSES)
NODE_CLASS_MAPPINGS.update(VIDEO_NODE_CLASSES)
NODE_CLASS_MAPPINGS.update(FILTER_NODE_CLASSES)
NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(SORT_NODE_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_NODE_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(FILTER_NODE_NAMES)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
